name: nightly-db-dump

on:
  schedule:
    - cron: "0 4 * * *"   # 04:00 UTC daily
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure required vars
        run: |
          : "${{ secrets.DB_HOST:?Missing DB_HOST }}"
          : "${{ secrets.DB_PORT:?Missing DB_PORT }}"
          : "${{ secrets.DB_USER:?Missing DB_USER }}"
          : "${{ secrets.DB_NAME:?Missing DB_NAME }}"
          : "${{ secrets.DB_PASSWORD:?Missing DB_PASSWORD }}"

      - name: Connectivity check
        env:
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          psql -h "${{ secrets.DB_HOST }}" -p "${{ secrets.DB_PORT }}" \
               -U "${{ secrets.DB_USER }}" -d "${{ secrets.DB_NAME }}" \
               -c "SELECT 1;"

      - name: Dump database
        env:
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          ts=$(date -u +'%Y%m%dT%H%M%SZ')
          pg_dump -h "${{ secrets.DB_HOST }}" -p "${{ secrets.DB_PORT }}" \
                  -U "${{ secrets.DB_USER }}" -d "${{ secrets.DB_NAME }}" \
                  --format=custom --no-owner --no-privileges \
                  --file "dump_${ts}.pgc"
          echo "artifact=dump_${ts}.pgc" >> $GITHUB_OUTPUT
        id: dump

      - name: Upload dump
        uses: actions/upload-artifact@v4
        with:
          name: pg-dump
          path: ${{ steps.dump.outputs.artifact }}
          if-no-files-found: error

