jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      # ↓ Add this DNS check step here
      - name: DNS check for PGHOST
        env:
          PGHOST: ${{ secrets.PGHOST }}
        run: |
          docker run --rm -e PGHOST busybox sh -lc '
            echo "PGHOST=$PGHOST";
            nslookup "$PGHOST" || echo "nslookup failed";
            getent hosts "$PGHOST" || echo "getent failed"
          '

      # Existing connectivity check
      - name: psql connectivity check
        env:
          PGHOST:     ${{ secrets.PGHOST }}
          PGPORT:     ${{ secrets.PGPORT }}
          PGUSER:     ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGSSLMODE:  require
        run: |
          docker run --rm \
            -e PGHOST -e PGPORT -e PGUSER -e PGPASSWORD -e PGDATABASE -e PGSSLMODE \
            postgres:17 bash -lc 'psql -c "\conninfo"'

      # Dump step…
      - name: Dump with dockerized pg_dump 17
        env:
          PGHOST:     ${{ secrets.PGHOST }}
          PGPORT:     ${{ secrets.PGPORT }}
          PGUSER:     ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGSSLMODE:  require
        run: |
          docker run --rm -v "$PWD:/dump" \
            -e PGHOST -e PGPORT -e PGUSER -e PGPASSWORD -e PGDATABASE -e PGSSLMODE \
            postgres:17 bash -lc 'pg_dump --format=custom --no-owner -f /dump/backup.dump'
