name: Nightly DB backup

on:
  schedule:
    - cron: "0 4 * * *"   # 04:00 UTC nightly
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      # If your DB is reachable over the internet (not localhost), use this:
      - name: Dump with dockerized pg_dump 17
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          docker run --rm -v "$PWD:/dump" -e DATABASE_URL postgres:17 \
            bash -lc 'pg_dump "$DATABASE_URL" -Fc -f /dump/backup.dump'

      # If your DATABASE_URL points to localhost/127.0.0.1 on the runner,
      # use host networking instead:
      # - name: Dump with dockerized pg_dump 17 (host network)
      #   env:
      #     DATABASE_URL: ${{ secrets.DATABASE_URL }}
      #   run: |
      #     docker run --rm --network host -v "$PWD:/dump" -e DATABASE_URL postgres:17 \
      #       bash -lc 'pg_dump "$DATABASE_URL" -Fc -f /dump/backup.dump'

      - name: Upload backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: db-backup
          path: backup.dump
          if-no-files-found: error
