- name: Install PostgreSQL 17 client
  run: |
    sudo apt-get update
    sudo apt-get install -y postgresql-client-17
    echo "/usr/lib/postgresql/17/bin" >> "$GITHUB_PATH"

- name: Verify pg_dump version
  run: |
    which pg_dump
    pg_dump --version

- name: Dump database
  env:
    DATABASE_URL: ${{ secrets.DATABASE_URL }}
  run: |
    pg_dump "$DATABASE_URL" -Fc -f backup.dump
