      - name: Connectivity + dump
        id: db
        shell: bash
        env:
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          set -euo pipefail

          DB_PORT="${DB_PORT:-5432}"

          echo "Installing PostgreSQL 17 client tools..."
          sudo apt-get update -qq
          sudo apt-get install -y -qq postgresql-client-17

          echo "Testing connectivity ..."
          psql "host=$DB_HOST port=$DB_PORT user=$DB_USER dbname=$DB_NAME sslmode=require" -c "SELECT 1;"

          ts=$(date -u +'%Y%m%dT%H%M%SZ')
          outfile="dump_${ts}.pgc"

          echo "Running pg_dump with version 17..."
          pg_dump "host=$DB_HOST port=$DB_PORT user=$DB_USER dbname=$DB_NAME sslmode=require" \
            --format=custom --no-owner --no-privileges --file "$outfile"

          echo "outfile=$outfile" >> "$GITHUB_OUTPUT"
