name: Nightly DB backup

on:
  schedule:
    - cron: "0 7 * * *"    # 07:00 UTC daily
  workflow_dispatch:

permissions:
  contents: write

concurrency: nightly-db-backup
env:
  PG_MAJOR: 17

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Quick connection test (psql over URI)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          docker run --rm -e DATABASE_URL postgres:${{ env.PG_MAJOR }}-alpine \
            psql "$DATABASE_URL?sslmode=require" -c "select 1"

      - name: Dump Postgres (compressed, custom format)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          TS=$(date -u +%Y-%m-%dT%H-%M-%SZ)
          docker run --rm -e DATABASE_URL -v "$PWD:/dump" \
            postgres:${{ env.PG_MAJOR }}-alpine \
            sh -lc 'pg_dump "$DATABASE_URL?sslmode=require" -F c -Z 9 -f "/dump/db_'"$TS"'".dump'

      - name: Upload artifact (90 days)
        uses: actions/upload-artifact@v4
        with:
          name: db-backup
          path: db_*.dump
          retention-days: 90
