name: Nightly DB backup

on:
  schedule:
    - cron: "0 6 * * *"   # 06:00 UTC daily
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: db-backup
  cancel-in-progress: true

jobs:
  dump:
    runs-on: ubuntu-22.04   # << cheaper Linux runner
    timeout-minutes: 20

    steps:
      - name: Validate secret exists
        env:
          DATABASE_URL_BACKUP: ${{ secrets.DATABASE_URL_BACKUP }}
        run: |
          test -n "$DATABASE_URL_BACKUP" || (echo "ERROR: missing DATABASE_URL_BACKUP secret" >&2; exit 1)

      - name: Install pg client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Test DB connection
        env:
          DATABASE_URL_BACKUP: ${{ secrets.DATABASE_URL_BACKUP }}
        run: |
          psql "$DATABASE_URL_BACKUP" -v ON_ERROR_STOP=1 -c "select current_user, current_database();"

      - name: Dump Postgres (compressed)
        env:
          DATABASE_URL_BACKUP: ${{ secrets.DATABASE_URL_BACKUP }}
        run: |
          set -euo pipefail
          TS=$(date -u +%Y%m%d-%H%M%S)
          FILE="backup-${TS}.dump"
          pg_dump "$DATABASE_URL_BACKUP" -Z 9 -Fc -f "$FILE"
          echo "FILE=$FILE" >> "$GITHUB_ENV"

      - name: Upload artifact (90 days)
        uses: actions/upload-artifact@v4
        with:
          name: neon-backup
          path: ${{ env.FILE }}
          retention-days: 90
