name: Nightly DB backup

on:
  schedule:
    - cron: "0 7 * * *"      # every day at 07:00 UTC
  workflow_dispatch:         # allow manual run

jobs:
  dump:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Dump database
        env:
          PGHOST: ${{ secrets.PGHOST }}
          PGPORT: ${{ secrets.PGPORT }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGUSER: ${{ secrets.PGUSER }}
        run: |
          set -euo pipefail
          TS=$(date -u +'%Y%m%dT%H%M%SZ')
          CONN="host=$PGHOST port=$PGPORT dbname=$PGDATABASE user=$PGUSER password=${{ secrets.PGPASSWORD }} sslmode=require"
          pg_dump "$CONN" --format=custom --no-owner --no-privileges \
            | gzip -c > "backup_${TS}.dump.gz"

      - name: Upload backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: postgres-backup
          path: backup_*.dump.gz
          retention-days: 7
