name: Nightly DB backup

on:
  schedule:
    - cron: "0 7 * * *"   # 07:00 UTC daily
  workflow_dispatch:       # allow manual runs

permissions:
  contents: write          # needed to upload artifacts

concurrency: nightly-db-backup

env:
  PG_MAJOR: 17             # single place to bump later

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Quick connection test (psql)
        env:
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
        run: |
          docker run --rm -e PGPASSWORD="$PGPASSWORD" postgres:${{ env.PG_MAJOR }}-alpine \
            psql -h "${{ secrets.PGHOST }}" -p "${{ secrets.PGPORT }}" -U "${{ secrets.PGUSER }}" -d "${{ secrets.PGDATABASE }}" -c "select 1"

      - name: Dump Postgres (compressed custom format)
        env:
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
        run: |
          TS=$(date -u +%Y-%m-%dT%H-%M-%SZ)
          docker run --rm \
            -e PGPASSWORD="$PGPASSWORD" \
            -v "$PWD:/dump" \
            postgres:${{ env.PG_MAJOR }}-alpine \
            pg_dump -h "${{ secrets.PGHOST }}" -p "${{ secrets.PGPORT }}" -U "${{ secrets.PGUSER }}" -d "${{ secrets.PGDATABASE }}" \
                    -F c -Z 9 -f "/dump/db_${TS}.dump"

      - name: Upload artifact (90 days)
        uses: actions/upload-artifact@v4
        with:
          name: db-backup
          path: db_*.dump
          retention-days: 90
