name: Supabase DB Dump

on:
  workflow_dispatch: {}

jobs:
  dump:
    runs-on: ubuntu-latest
    env:
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_DB:   ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    steps:
      - name: Preflight: sanitize and DNS check
        run: |
          set -e
          CLEAN_HOST=$(printf "%s" "$POSTGRES_HOST" | tr -d '\r\n\t ')
          echo "Using sanitized host"
          getent hosts "$CLEAN_HOST" >/dev/null || (echo "DNS lookup failed for $CLEAN_HOST"; exit 1)
          echo "CLEAN_HOST=$CLEAN_HOST" >> $GITHUB_ENV

      - name: Dump using Postgres 17 (Docker) with SSL
        run: |
          set -e
          TS=$(date -u +'%Y%m%dT%H%M%SZ')
          FILE="supabase_dump_${TS}.dump"

          docker run --rm \
            -e PGPASSWORD="${POSTGRES_PASSWORD}" \
            -v "$PWD:/out" \
            postgres:17-alpine \
            sh -c 'pg_dump "host='"${CLEAN_HOST}"' port='"${POSTGRES_PORT}"' dbname='"${POSTGRES_DB}"' user='"${POSTGRES_USER}"' sslmode=require" \
                   --format=custom --no-owner --no-privileges -f /out/'"$FILE"

          ls -lh "$FILE"

      - name: Upload dump artifact
        uses: actions/upload-artifact@v4
        with:
          name: supabase-dump
          path: "*.dump"
          retention-days: 7
