name: Supabase DB Dump

on:
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-latest

    steps:
      - name: Dump using Postgres 17 (Docker) with SSL
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}   # e.g. postgresql://postgres:PASSWORD@db.<ref>.supabase.co:5432/postgres
        run: |
          set -euo pipefail

          # Ensure sslmode=require is present
          if [[ "$DATABASE_URL" == *"?"* ]]; then
            CONN="${DATABASE_URL}&sslmode=require"
          else
            CONN="${DATABASE_URL}?sslmode=require"
          fi

          TS=$(date -u +'%Y%m%dT%H%M%SZ')
          FILE="supabase_dump_${TS}.dump"

          docker run --rm -v "$PWD:/out" postgres:17-alpine \
            sh -lc "pg_dump \"$CONN\" --format=custom --no-owner --no-privileges -f /out/$FILE"

          ls -lh "$FILE"

      - name: Upload dump artifact
        uses: actions/upload-artifact@v4
        with:
          name: supabase-dump
          path: "*.dump"
          retention-days: 7
