name: Supabase DB Dump

on:
  workflow_dispatch: {}

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Dump Supabase database (SSL required)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          set -e
          # Ensure sslmode=require is present
          if [[ "$DATABASE_URL" == *"?"* ]]; then
            CONN_STR="${DATABASE_URL}&sslmode=require"
          else
            CONN_STR="${DATABASE_URL}?sslmode=require"
          fi

          TS=$(date -u +'%Y%m%dT%H%M%SZ')
          FILE="supabase_dump_${TS}.dump"

          pg_dump "$CONN_STR" --format=custom --no-owner --no-privileges -f "$FILE"
          echo "Created dump: $FILE"
          ls -lh "$FILE"

      - name: Upload dump artifact
        uses: actions/upload-artifact@v4
        with:
          name: supabase-dump
          path: "*.dump"
          retention-days: 7
