name: Supabase DB Dump

on:
  workflow_dispatch: {}

jobs:
  dump:
    runs-on: ubuntu-latest

    env:
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}       # e.g. db.xxxxx.supabase.co
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}       # 5432
      POSTGRES_DB:   ${{ secrets.POSTGRES_DB }}         # usually "postgres"
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}       # usually "postgres"
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: Dump using Postgres 17 (Docker) with SSL
        run: |
          set -e
          TS=$(date -u +'%Y%m%dT%H%M%SZ')
          FILE="supabase_dump_${TS}.dump"

          docker run --rm \
            -e PGPASSWORD="${POSTGRES_PASSWORD}" \
            -v "$PWD:/out" \
            postgres:17-alpine \
            sh -c 'pg_dump "host='"${POSTGRES_HOST}"' port='"${POSTGRES_PORT}"' dbname='"${POSTGRES_DB}"' user='"${POSTGRES_USER}"' sslmode=require" \
                   --format=custom --no-owner --no-privileges -f /out/'"$FILE"

          ls -lh "$FILE"

      - name: Upload dump artifact
        uses: actions/upload-artifact@v4
        with:
          name: supabase-dump
          path: "*.dump"
          retention-days: 7
