name: upstash-keepalive
on:
  schedule:
    - cron: '0 7 * * 1'   # weekly
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Sanity check secrets
        env:
          URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          TOKEN: ${{ secrets.UPSTASH_REST_TOKEN }}
        run: |
          set -e
          test -n "$URL" || (echo "ERROR: UPSTASH_REDIS_REST_URL is empty"; exit 1)
          test -n "$TOKEN" || (echo "ERROR: UPSTASH_REST_TOKEN is empty"; exit 1)
          echo "Using URL: $URL"

      - name: Ping Upstash (expect PONG)
        env:
          URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          TOKEN: ${{ secrets.UPSTASH_REST_TOKEN }}
        run: |
          curl -fsS -H "Authorization: Bearer $TOKEN" "$URL/ping"

